# Generated by Django 3.0.11 on 2021-01-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210126_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_inquiry',
            field=models.BooleanField(db_column='Is_Inquiry', default=False, help_text='Designates whether this user should be treated as an inquiry.', verbose_name='inquiry'),
        ),
    ]
